import { useInView } from '../hooks/useInView'
import './ENoseSection.css'

export default function ENoseSection() {
  const [ref, isInView] = useInView()

  return (
    <section id="e-nose" className={`e-nose-panel ${isInView ? 'animate' : ''}`} ref={ref}>
      <div className="e-nose-container">
        <div className="e-nose-heading">
          <h2>ELE-SCENT E-nose</h2>
        </div>

        <div className="e-nose-text glass-panel">
          <p>
            The initial prototype showed successful integration, and the sensors captured dynamic changes in VOCs and environmental conditions. This was a major milestone in verifying that the initial design and implementation worked correctly with the sensors and microcontroller. The first prototype e-nose was assembled on a breadboard, with all components connected to the ESP32 microcontroller through wires. Although the breadboard prototype functioned as expected, there was still significant room for improvement. The components were then moved onto a custom-designed PCB, replacing the breadboard setup. The e-nose was further improved with a sensor chamber and airflow control.
          </p>
          <p>
            To ensure the electronic nose was robust enough for real-world ground testing and field deployment, a custom hardware enclosure was engineered. The primary design goal was to separate the core computing components from the sensing elements in order to reduce electrical glitches, heat interference, and accidental data misinterpretation. The new enclosure features an isolated standalone air chamber dedicated to the gas sensor array. Attached directly to this sensing chamber is a small ventilation cooling fan. This fan plays a critical role by actively pulling fresh air samples across the sensors during tracking cycles and quickly purging the chamber after a detection event, preventing stagnant gases from lingering and causing false readings. By isolating the sensor array from the heat generated by the microcontroller, the system maintains a stable ambient operating temperature. This finalized, industrial-grade e-nose device was successfully deployed in the field for long-term data collection and live environmental testing.
          </p>
        </div>

        <div className="e-nose-timeline" aria-label="ELE-SCENT E-nose prototype timeline">
          <div className="e-nose-timeline-line" />

          <article className="e-nose-timeline-item">
            <div className="e-nose-timeline-label">Initial</div>
            <div className="e-nose-timeline-image-frame">
              <img src="/images/d1.jpg" alt="Initial ELE-SCENT E-nose prototype" className="e-nose-timeline-image" />
            </div>
          </article>

          <article className="e-nose-timeline-item">
            <div className="e-nose-timeline-label">Intermediate</div>
            <div className="e-nose-timeline-image-frame">
              <img src="/images/d2.jpg" alt="Intermediate ELE-SCENT E-nose prototype" className="e-nose-timeline-image" />
            </div>
          </article>

          <article className="e-nose-timeline-item is-final">
            <div className="e-nose-timeline-label">Latest and Final</div>
            <div className="e-nose-timeline-image-frame">
              <img src="/images/d3.jpg" alt="Final ELE-SCENT E-nose prototype" className="e-nose-timeline-image" />
            </div>
          </article>
        </div>
      </div>
    </section>
  )
}